### ISSUE TITLE
PKG power limit

### ISSUE THREAD

**Issue by cswb120** [powercap/raplcap#4]
Hi, 

after i set the PKG power limit to 55 watts and run an application whose peak power is over this value, the measured power consumption is about 50 watts, i.e. 5 watts difference. What is happening? 

Hardware: Broadwell E5-2650V4
Release 0.1.1
RAPL setting: two time windows with 1 seconds, PKG to 55 watts 
Measured power with: perf stat .... sleep 1

Best, 
Bo

**Comment by connorimes** [comment]
Hello.  This doesn't seem to be a bug, but rather a question about RAPL.

There are multiple things to consider.  First, the system doesn't have to use all the power you allocate to it - it is a power *cap* not the actual power *consumption*.  Second is whether you set the *long term* or *short term* limit, and what the value of the other is.  Typically the short term limit should be higher as it provides a stricter upper bound on power, but should have a shorter time window.  This allows the processor to run faster and hotter for short bursts (e.g. using TurboBoost) while keeping power low on average.  It probably doesn't make sense to set both limits to the same time window and/or power limit values.

If all you're doing is sleeping, the power should definitely be lower than the cap since no work is actually being performed, except by background tasks.  Also consider sleeping for longer than 1 second, you might see the power reduce even more.
