### ISSUE TITLE
raplcap_set_zone_enabled in README

### ISSUE THREAD

**Issue by DanieleDeSensi** [powercap/raplcap#7]
Hi, 
I tried to use the library on my system by using the example provided in the README. 
However, to let it work I had to add 'raplcap_set_zone_enabled(..)' before setting the cap. Adding it to the example would probably be helpful for other users.

Best,
Daniele

**Comment by connorimes** [comment]
Hi Daniele, thanks for the feedback.  It's good to hear from you - I hope you're well.  Can you please provide more information like which library implementation you're using (`msr` or `powercap`), what zone(s) you're trying to set, and what Intel CPU you're running on?  Also, what are the original power and timing limits before you first try to set/enable?

Setting the limits and the enabled status should be orthogonal operations.  I would think the typical use case would be to configure limits _before_ enabling, so that you don't enable into an unknown/undesirable state.  (Similarly, if configuring fails for some reason, then the SW should not try to enable.)  Perhaps some hardware rejects enabling if, for example, the power limit is set to 0.  I have not seen any documentation that describes an expected order of operations though.

**Comment by DanieleDeSensi** [comment]
Hi Connor, nice to hear from you as well, will you be at SC this year? :)
Thank you for the feedback. I didn't try yet to enable it after configuring the limits but I think that will work as well. My suggestion was not about the specific order of the calls, but just about mentioning in the README that to actually set the power cap, raplcap_set_zone_enabled should be called before or after calling the raplcap_set_limits.
I mean, I think the code is working well, my suggestion was just to make the README clearer on the need to enable the limits (even though this is already clear from the documentation in the header file).

**Comment by connorimes** [comment]
Unfortunately I will not be attending SC this year.  If you're ever in the Washington D.C. area though, let me know!

I'm glad there's not a technical problem, b/c I'm not sure there would be a clean way to address it except through documentation.  I will update the README sometime to include something along those lines.  You're also welcome to submit PRs if you wish, even just to improve documentation.  I'll leave this issue open until the README is updated.

Cheers.

**Comment by DanieleDeSensi** [comment]
Ok, I'll open a PR ;)

**Comment by connorimes** [comment]
As it turns out I _will_ be at SC this year -- I'll see you in Denver!
